const fs = require('fs');

function replaceLinesInFile(filePath, replacements) {
  let content = fs.readFileSync(filePath, 'utf8');
  const isCrlf = content.includes('\r\n');
  let normalized = content.replace(/\r\n/g, '\n');

  replacements.forEach(([targetLines, replLines], idx) => {
    const target = targetLines.join('\n');
    const repl = replLines.join('\n');
    if (!normalized.includes(target)) {
      console.error(`Target not found in ${filePath} at index ${idx}:\nFIRST LINE: ${targetLines[0]}`);
      process.exit(1);
    }
    normalized = normalized.replace(target, repl);
  });

  const finalContent = isCrlf ? normalized.replace(/\n/g, '\r\n') : normalized;
  fs.writeFileSync(filePath, finalContent, 'utf8');
  console.log(`Successfully updated ${filePath}`);
}

// ========================================================
// 1. AcademicYearsPage.tsx
// ========================================================
{
  const file = 'src/features/master/AcademicYearsPage.tsx';
  const replacements = [
    // Header title & subtitle
    [
      [
        '          <h1 className="text-xl font-bold text-slate-800 dark:text-zinc-100 tracking-tight flex items-center gap-2">',
        '            <CalendarBlank className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />',
        '            Master Tahun Ajaran',
        '          </h1>',
        '          <p className="text-xs text-slate-500 dark:text-zinc-400 mt-1">'
      ],
      [
        '          <h1 className="text-xl font-bold text-[var(--ds-text)] tracking-tight flex items-center gap-2">',
        '            <CalendarBlank className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />',
        '            Master Tahun Ajaran',
        '          </h1>',
        '          <p className="text-xs text-[var(--ds-text-muted)] mt-1">'
      ]
    ],
    // Filter tabs container & tab buttons
    [
      [
        '          {/* Tabs Filter */}',
        '          <div className="flex bg-slate-100 dark:bg-neutral-900 p-1 rounded-xl border border-slate-200 dark:border-neutral-800 text-xs">',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ACTIVE\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ACTIVE\'',
        '                  ? \'bg-white dark:bg-neutral-800 text-slate-900 dark:text-white shadow-xs\'',
        '                  : \'text-slate-500 hover:text-slate-800 dark:text-zinc-400\'',
        '              }`}',
        '            >',
        '              Aktif ({academicYears.filter(y => !y.isArchived).length})',
        '            </button>',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ARCHIVED\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ARCHIVED\'',
        '                  ? \'bg-white dark:bg-neutral-800 text-slate-900 dark:text-white shadow-xs\'',
        '                  : \'text-slate-500 hover:text-slate-800 dark:text-zinc-400\'',
        '              }`}',
        '            >',
        '              Arsip ({academicYears.filter(y => y.isArchived).length})',
        '            </button>',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ALL\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ALL\'',
        '                  ? \'bg-white dark:bg-neutral-800 text-slate-900 dark:text-white shadow-xs\'',
        '                  : \'text-slate-500 hover:text-slate-800 dark:text-zinc-400\'',
        '              }`}',
        '            >',
        '              Semua ({academicYears.length})',
        '            </button>',
        '          </div>'
      ],
      [
        '          {/* Tabs Filter */}',
        '          <div className="flex bg-[var(--ds-surface-muted)] p-1 rounded-xl border border-[var(--ds-border)] text-xs">',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ACTIVE\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ACTIVE\'',
        '                  ? \'bg-[var(--ds-surface-elevated)] text-[var(--ds-text)] shadow-xs\'',
        '                  : \'text-[var(--ds-text-muted)] hover:text-[var(--ds-text)]\'',
        '              }`}',
        '            >',
        '              Aktif ({academicYears.filter(y => !y.isArchived).length})',
        '            </button>',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ARCHIVED\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ARCHIVED\'',
        '                  ? \'bg-[var(--ds-surface-elevated)] text-[var(--ds-text)] shadow-xs\'',
        '                  : \'text-[var(--ds-text-muted)] hover:text-[var(--ds-text)]\'',
        '              }`}',
        '            >',
        '              Arsip ({academicYears.filter(y => y.isArchived).length})',
        '            </button>',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ALL\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ALL\'',
        '                  ? \'bg-[var(--ds-surface-elevated)] text-[var(--ds-text)] shadow-xs\'',
        '                  : \'text-[var(--ds-text-muted)] hover:text-[var(--ds-text)]\'',
        '              }`}',
        '            >',
        '              Semua ({academicYears.length})',
        '            </button>',
        '          </div>'
      ]
    ],
    // Empty state
    [
      [
        '      {/* Grid of Academic Years */}',
        '      {filteredYears.length === 0 ? (',
        '        <div className="bg-white dark:bg-neutral-950 border border-dashed border-slate-200 dark:border-neutral-800 rounded-3xl p-10 text-center">',
        '          <CalendarBlank className="w-8 h-8 text-slate-400 mx-auto mb-2" />',
        '          <p className="text-xs font-semibold text-slate-600 dark:text-zinc-300">'
      ],
      [
        '      {/* Grid of Academic Years */}',
        '      {filteredYears.length === 0 ? (',
        '        <div className="bg-[var(--ds-surface)] border border-dashed border-[var(--ds-border)] rounded-3xl p-10 text-center">',
        '          <CalendarBlank className="w-8 h-8 text-[var(--ds-text-muted)] mx-auto mb-2" />',
        '          <p className="text-xs font-semibold text-[var(--ds-text-muted)]">'
      ]
    ],
    // Card item wrapper
    [
      [
        '              <div',
        '                key={year.id}',
        '                className={`p-5 rounded-2xl border transition-all flex flex-col justify-between ${',
        '                  isArchived',
        '                    ? \'bg-slate-50 dark:bg-neutral-900/50 border-dashed border-slate-300 dark:border-neutral-800 opacity-80\'',
        '                    : isCurrentActive',
        '                    ? \'bg-white dark:bg-neutral-950 border-emerald-300 dark:border-emerald-500/40 ring-2 ring-emerald-500/20 dark:ring-emerald-500/20 shadow-sm\'',
        '                    : \'bg-white dark:bg-neutral-950 border-slate-200 dark:border-neutral-800 hover:border-slate-300\'',
        '                }`}',
        '              >'
      ],
      [
        '              <div',
        '                key={year.id}',
        '                className={`p-5 rounded-2xl border transition-all flex flex-col justify-between ${',
        '                  isArchived',
        '                    ? \'bg-[var(--ds-surface-muted)] border-dashed border-[var(--ds-border)] opacity-80\'',
        '                    : isCurrentActive',
        '                    ? \'bg-[var(--ds-surface)] border-emerald-300 dark:border-emerald-500/40 ring-2 ring-emerald-500/20 dark:ring-emerald-500/20 shadow-sm\'',
        '                    : \'bg-[var(--ds-surface)] border-[var(--ds-border)] hover:border-[var(--ds-text-muted)]\'',
        '                }`}',
        '              >'
      ]
    ],
    // "Set Aktif" button
    [
      [
        '                        <button',
        '                          type="button"',
        '                          onClick={() => handleSetActive(year.id, year.label)}',
        '                          className="text-xs font-semibold text-slate-500 hover:text-emerald-600 dark:hover:text-emerald-400 cursor-pointer"',
        '                        >',
        '                          Set Aktif',
        '                        </button>'
      ],
      [
        '                        <button',
        '                          type="button"',
        '                          onClick={() => handleSetActive(year.id, year.label)}',
        '                          className="text-xs font-semibold text-[var(--ds-text-muted)] hover:text-emerald-600 dark:hover:text-emerald-400 cursor-pointer"',
        '                        >',
        '                          Set Aktif',
        '                        </button>'
      ]
    ],
    // Card typography
    [
      [
        '                  <h3 className="font-bold text-base text-slate-800 dark:text-zinc-100">{year.label}</h3>',
        '                  <p className="text-xs text-slate-500 dark:text-zinc-400 mt-1">',
        '                    Semester Berjalan: <span className="font-semibold text-slate-700 dark:text-zinc-300">{year.currentSemester}</span>',
        '                  </p>',
        '                  <p className="text-[11px] text-slate-400 dark:text-zinc-500 mt-0.5">'
      ],
      [
        '                  <h3 className="font-bold text-base text-[var(--ds-text)]">{year.label}</h3>',
        '                  <p className="text-xs text-[var(--ds-text-muted)] mt-1">',
        '                    Semester Berjalan: <span className="font-semibold text-[var(--ds-text)]">{year.currentSemester}</span>',
        '                  </p>',
        '                  <p className="text-[11px] text-[var(--ds-text-muted)] mt-0.5">'
      ]
    ],
    // Card footer divider & actions
    [
      [
        '                {/* Actions Footer */}',
        '                <div className="mt-4 pt-3 border-t border-slate-100 dark:border-neutral-800 flex items-center justify-between">',
        '                  <span className={`text-[11px] font-medium ${isArchived ? \'text-amber-600 dark:text-amber-400\' : isCurrentActive ? \'text-emerald-600 dark:text-emerald-400\' : \'text-slate-400\'}`}>',
        '                    {isArchived ? \'Tahun Ajaran Arsip\' : isCurrentActive ? \'Sedang Digunakan\' : \'Tahun Ajaran Inaktif\'}',
        '                  </span>',
        '',
        '                  <div className="flex items-center gap-1">',
        '                    {!isArchived ? (',
        '                      <>',
        '                        <button',
        '                          type="button"',
        '                          onClick={() => handleOpenEdit(year)}',
        '                          className="p-1.5 rounded-lg text-slate-400 hover:text-emerald-600 dark:hover:text-emerald-400 hover:bg-slate-100 dark:hover:bg-neutral-800 transition-colors cursor-pointer"',
        '                          title="Edit Tahun Ajaran"',
        '                        >',
        '                          <PencilSimple className="w-4 h-4" />',
        '                        </button>',
        '                        {!isCurrentActive && (',
        '                          <button',
        '                            type="button"',
        '                            disabled={archiving}',
        '                            onClick={() => handleArchive(year)}',
        '                            className="p-1.5 rounded-lg text-slate-400 hover:text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950/40 transition-colors cursor-pointer"',
        '                            title="Arsipkan Tahun Ajaran"',
        '                          >',
        '                            <Archive className="w-4 h-4" />',
        '                          </button>',
        '                        )}',
        '                      </>',
        '                    ) : (',
        '                      <button',
        '                        type="button"',
        '                        disabled={archiving}',
        '                        onClick={() => handleUnarchive(year)}',
        '                        className="px-2 py-1 rounded-lg text-xs font-semibold text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60 flex items-center gap-1 transition-colors cursor-pointer"',
        '                        title="Pulihkan dari Arsip"',
        '                      >',
        '                        <ArrowCounterClockwise className="w-3.5 h-3.5" />',
        '                        <span>Pulihkan</span>',
        '                      </button>',
        '                    )}',
        '',
        '                    {!isCurrentActive && (',
        '                      <button',
        '                        type="button"',
        '                        onClick={() => handleRequestDelete(year)}',
        '                        className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 transition-colors cursor-pointer"',
        '                        title="Hapus Tahun Ajaran"',
        '                      >',
        '                        <Trash className="w-4 h-4" />',
        '                      </button>',
        '                    )}',
        '                  </div>',
        '                </div>'
      ],
      [
        '                {/* Actions Footer */}',
        '                <div className="mt-4 pt-3 border-t border-[var(--ds-border)] flex items-center justify-between">',
        '                  <span className={`text-[11px] font-medium ${isArchived ? \'text-amber-600 dark:text-amber-400\' : isCurrentActive ? \'text-emerald-600 dark:text-emerald-400\' : \'text-[var(--ds-text-muted)]\'}`}>',
        '                    {isArchived ? \'Tahun Ajaran Arsip\' : isCurrentActive ? \'Sedang Digunakan\' : \'Tahun Ajaran Inaktif\'}',
        '                  </span>',
        '',
        '                  <div className="flex items-center gap-1">',
        '                    {!isArchived ? (',
        '                      <>',
        '                        <button',
        '                          type="button"',
        '                          onClick={() => handleOpenEdit(year)}',
        '                          className="p-1.5 rounded-lg text-[var(--ds-text-muted)] hover:text-emerald-600 dark:hover:text-emerald-400 hover:bg-[var(--ds-surface-muted)] transition-colors cursor-pointer"',
        '                          title="Edit Tahun Ajaran"',
        '                        >',
        '                          <PencilSimple className="w-4 h-4" />',
        '                        </button>',
        '                        {!isCurrentActive && (',
        '                          <button',
        '                            type="button"',
        '                            disabled={archiving}',
        '                            onClick={() => handleArchive(year)}',
        '                            className="p-1.5 rounded-lg text-[var(--ds-text-muted)] hover:text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950/40 transition-colors cursor-pointer"',
        '                            title="Arsipkan Tahun Ajaran"',
        '                          >',
        '                            <Archive className="w-4 h-4" />',
        '                          </button>',
        '                        )}',
        '                      </>',
        '                    ) : (',
        '                      <button',
        '                        type="button"',
        '                        disabled={archiving}',
        '                        onClick={() => handleUnarchive(year)}',
        '                        className="px-2 py-1 rounded-lg text-xs font-semibold text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60 flex items-center gap-1 transition-colors cursor-pointer"',
        '                        title="Pulihkan dari Arsip"',
        '                      >',
        '                        <ArrowCounterClockwise className="w-3.5 h-3.5" />',
        '                        <span>Pulihkan</span>',
        '                      </button>',
        '                    )}',
        '',
        '                    {!isCurrentActive && (',
        '                      <button',
        '                        type="button"',
        '                        onClick={() => handleRequestDelete(year)}',
        '                        className="p-1.5 rounded-lg text-[var(--ds-text-muted)] hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 transition-colors cursor-pointer"',
        '                        title="Hapus Tahun Ajaran"',
        '                      >',
        '                        <Trash className="w-4 h-4" />',
        '                      </button>',
        '                    )}',
        '                  </div>',
        '                </div>'
      ]
    ],
    // Modal Add/Edit inputs
    [
      [
        '            <label className="block text-xs font-semibold text-slate-700 dark:text-zinc-300 mb-1.5 flex items-center justify-between">',
        '              <span>Label Tahun Ajaran <span className="text-rose-500">*</span></span>',
        '              {yearUsage?.isUsed && (',
        '                <span className="text-[10px] text-amber-600 dark:text-amber-400 font-normal flex items-center gap-1">',
        '                  <Lock className="w-3 h-3" /> Terkunci (Ada Data)',
        '                </span>',
        '              )}',
        '            </label>',
        '            <input',
        '              type="text"',
        '              required',
        '              disabled={Boolean(yearUsage?.isUsed)}',
        '              value={label}',
        '              onChange={e => setLabel(e.target.value)}',
        '              placeholder="Contoh: 2026/2027"',
        '              className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 text-xs focus:ring-2 focus:ring-emerald-500 disabled:opacity-60 disabled:bg-slate-100 dark:disabled:bg-neutral-800"',
        '            />',
        '          </div>',
        '',
        '          <div className="grid grid-cols-2 gap-3">',
        '            <div>',
        '              <label className="block text-xs font-semibold text-slate-700 dark:text-zinc-300 mb-1.5 flex items-center justify-between">',
        '                <span>Tahun Mulai</span>',
        '                {yearUsage?.isUsed && <Lock className="w-3 h-3 text-amber-500" />}',
        '              </label>',
        '              <input',
        '                type="number"',
        '                disabled={Boolean(yearUsage?.isUsed)}',
        '                value={startYear}',
        '                onChange={e => setStartYear(Number(e.target.value))}',
        '                className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 text-xs disabled:opacity-60 disabled:bg-slate-100 dark:disabled:bg-neutral-800"',
        '              />',
        '            </div>',
        '            <div>',
        '              <label className="block text-xs font-semibold text-slate-700 dark:text-zinc-300 mb-1.5 flex items-center justify-between">',
        '                <span>Tahun Selesai</span>',
        '                {yearUsage?.isUsed && <Lock className="w-3 h-3 text-amber-500" />}',
        '              </label>',
        '              <input',
        '                type="number"',
        '                disabled={Boolean(yearUsage?.isUsed)}',
        '                value={endYear}',
        '                onChange={e => setEndYear(Number(e.target.value))}',
        '                className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 text-xs disabled:opacity-60 disabled:bg-slate-100 dark:disabled:bg-neutral-800"',
        '              />',
        '            </div>',
        '          </div>',
        '',
        '          <div>',
        '            <label className="block text-xs font-semibold text-slate-700 dark:text-zinc-300 mb-1.5">Semester Berjalan</label>',
        '            <select',
        '              value={currentSemester}',
        '              onChange={e => setCurrentSemester(e.target.value as \'GANJIL\' | \'GENAP\')}',
        '              className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 text-xs"',
        '            >',
        '              <option value="GANJIL">Semester Ganjil (1)</option>',
        '              <option value="GENAP">Semester Genap (2)</option>',
        '            </select>',
        '          </div>',
        '',
        '          <label className="flex items-center gap-2 text-xs text-slate-700 dark:text-zinc-300 cursor-pointer pt-1">',
        '            <input',
        '              type="checkbox"',
        '              checked={isActive}',
        '              onChange={e => setIsActive(e.target.checked)}',
        '              className="rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"',
        '            />',
        '            <span>Jadikan tahun ajaran aktif di workspace</span>',
        '          </label>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-slate-100 dark:border-neutral-800">',
        '            <button',
        '              type="button"',
        '              onClick={() => setModalOpen(false)}',
        '              className="px-3 py-2 rounded-xl text-slate-600 dark:text-zinc-300 hover:bg-slate-100 dark:hover:bg-neutral-800 text-xs font-medium cursor-pointer"',
        '            >'
      ],
      [
        '            <label className="block text-xs font-semibold text-[var(--ds-text)] mb-1.5 flex items-center justify-between">',
        '              <span>Label Tahun Ajaran <span className="text-rose-500">*</span></span>',
        '              {yearUsage?.isUsed && (',
        '                <span className="text-[10px] text-amber-600 dark:text-amber-400 font-normal flex items-center gap-1">',
        '                  <Lock className="w-3 h-3" /> Terkunci (Ada Data)',
        '                </span>',
        '              )}',
        '            </label>',
        '            <input',
        '              type="text"',
        '              required',
        '              disabled={Boolean(yearUsage?.isUsed)}',
        '              value={label}',
        '              onChange={e => setLabel(e.target.value)}',
        '              placeholder="Contoh: 2026/2027"',
        '              className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs focus:ring-2 focus:ring-emerald-500 disabled:opacity-60 disabled:bg-[var(--ds-surface-muted)]"',
        '            />',
        '          </div>',
        '',
        '          <div className="grid grid-cols-2 gap-3">',
        '            <div>',
        '              <label className="block text-xs font-semibold text-[var(--ds-text)] mb-1.5 flex items-center justify-between">',
        '                <span>Tahun Mulai</span>',
        '                {yearUsage?.isUsed && <Lock className="w-3 h-3 text-amber-500" />}',
        '              </label>',
        '              <input',
        '                type="number"',
        '                disabled={Boolean(yearUsage?.isUsed)}',
        '                value={startYear}',
        '                onChange={e => setStartYear(Number(e.target.value))}',
        '                className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs disabled:opacity-60 disabled:bg-[var(--ds-surface-muted)]"',
        '              />',
        '            </div>',
        '            <div>',
        '              <label className="block text-xs font-semibold text-[var(--ds-text)] mb-1.5 flex items-center justify-between">',
        '                <span>Tahun Selesai</span>',
        '                {yearUsage?.isUsed && <Lock className="w-3 h-3 text-amber-500" />}',
        '              </label>',
        '              <input',
        '                type="number"',
        '                disabled={Boolean(yearUsage?.isUsed)}',
        '                value={endYear}',
        '                onChange={e => setEndYear(Number(e.target.value))}',
        '                className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs disabled:opacity-60 disabled:bg-[var(--ds-surface-muted)]"',
        '              />',
        '            </div>',
        '          </div>',
        '',
        '          <div>',
        '            <label className="block text-xs font-semibold text-[var(--ds-text)] mb-1.5">Semester Berjalan</label>',
        '            <select',
        '              value={currentSemester}',
        '              onChange={e => setCurrentSemester(e.target.value as \'GANJIL\' | \'GENAP\')}',
        '              className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs"',
        '            >',
        '              <option value="GANJIL">Semester Ganjil (1)</option>',
        '              <option value="GENAP">Semester Genap (2)</option>',
        '            </select>',
        '          </div>',
        '',
        '          <label className="flex items-center gap-2 text-xs text-[var(--ds-text)] cursor-pointer pt-1">',
        '            <input',
        '              type="checkbox"',
        '              checked={isActive}',
        '              onChange={e => setIsActive(e.target.checked)}',
        '              className="rounded border-[var(--ds-border)] text-emerald-600 focus:ring-emerald-500"',
        '            />',
        '            <span>Jadikan tahun ajaran aktif di workspace</span>',
        '          </label>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-[var(--ds-border)]">',
        '            <button',
        '              type="button"',
        '              onClick={() => setModalOpen(false)}',
        '              className="px-3 py-2 rounded-xl text-[var(--ds-text-muted)] hover:text-[var(--ds-text)] hover:bg-[var(--ds-surface-muted)] text-xs font-medium cursor-pointer"',
        '            >'
      ]
    ],
    // Delete confirm dialog strong
    [
      [
        '            Apakah Anda yakin ingin menghapus tahun ajaran <strong className="font-semibold text-slate-800 dark:text-slate-100">&quot;{yearToDelete?.label}&quot;</strong>?'
      ],
      [
        '            Apakah Anda yakin ingin menghapus tahun ajaran <strong className="font-semibold text-[var(--ds-text)]">&quot;{yearToDelete?.label}&quot;</strong>?'
      ]
    ],
    // Delete blocked dialog
    [
      [
        '          <p className="text-xs text-slate-600 dark:text-zinc-400 leading-relaxed">',
        '            Menghapus tahun ajaran ini akan merusak integritas seluruh rekam kelas, rombel, nilai, dan absensi yang pernah tercatat.',
        '            Sebagai alternatif yang aman, Anda dapat <strong>mengarsipkan</strong> tahun ajaran ini sehingga tetap aman tersimpan untuk kebutuhan historis.',
        '          </p>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-slate-100 dark:border-neutral-800">',
        '            <button',
        '              type="button"',
        '              onClick={() => setDeleteBlockedModal(null)}',
        '              className="px-3 py-2 rounded-xl text-slate-600 dark:text-zinc-300 hover:bg-slate-100 dark:hover:bg-neutral-800 text-xs font-medium cursor-pointer"',
        '            >'
      ],
      [
        '          <p className="text-xs text-[var(--ds-text-muted)] leading-relaxed">',
        '            Menghapus tahun ajaran ini akan merusak integritas seluruh rekam kelas, rombel, nilai, dan absensi yang pernah tercatat.',
        '            Sebagai alternatif yang aman, Anda dapat <strong>mengarsipkan</strong> tahun ajaran ini sehingga tetap aman tersimpan untuk kebutuhan historis.',
        '          </p>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-[var(--ds-border)]">',
        '            <button',
        '              type="button"',
        '              onClick={() => setDeleteBlockedModal(null)}',
        '              className="px-3 py-2 rounded-xl text-[var(--ds-text-muted)] hover:text-[var(--ds-text)] hover:bg-[var(--ds-surface-muted)] text-xs font-medium cursor-pointer"',
        '            >'
      ]
    ]
  ];
  replaceLinesInFile(file, replacements);
}

// ========================================================
// 2. SubjectsPage.tsx
// ========================================================
{
  const file = 'src/features/master/SubjectsPage.tsx';
  const replacements = [
    // Header title & subtitle
    [
      [
        '          <h1 className="text-xl font-bold text-slate-800 dark:text-slate-100 tracking-tight flex items-center gap-2">',
        '            <BookOpen className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />',
        '            Master Mata Pelajaran',
        '          </h1>',
        '          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">'
      ],
      [
        '          <h1 className="text-xl font-bold text-[var(--ds-text)] tracking-tight flex items-center gap-2">',
        '            <BookOpen className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />',
        '            Master Mata Pelajaran',
        '          </h1>',
        '          <p className="text-xs text-[var(--ds-text-muted)] mt-1">'
      ]
    ],
    // Filter tabs container & search bar
    [
      [
        '      {/* Filter Tabs & MagnifyingGlass Bar */}',
        '      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-white dark:bg-slate-900 p-2.5 rounded-2xl border border-slate-200/90 dark:border-slate-800 shadow-2xs">',
        '        <div className="flex items-center gap-1 overflow-x-auto">',
        '          <button',
        '            type="button"',
        '            onClick={() => setFilterTab(\'ACTIVE\')}',
        '            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer whitespace-nowrap ${',
        '              filterTab === \'ACTIVE\'',
        '                ? \'bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800\'',
        '                : \'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800\'',
        '            }`}',
        '          >',
        '            Aktif ({activeCount})',
        '          </button>',
        '          <button',
        '            type="button"',
        '            onClick={() => setFilterTab(\'ARCHIVED\')}',
        '            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer whitespace-nowrap ${',
        '              filterTab === \'ARCHIVED\'',
        '                ? \'bg-amber-50 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border border-amber-200 dark:border-amber-800\'',
        '                : \'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800\'',
        '            }`}',
        '          >',
        '            Diarsipkan ({archivedCount})',
        '          </button>',
        '          <button',
        '            type="button"',
        '            onClick={() => setFilterTab(\'ALL\')}',
        '            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer whitespace-nowrap ${',
        '              filterTab === \'ALL\'',
        '                ? \'bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-700\'',
        '                : \'text-slate-600 dark:text-slate-400 hover:bg-slate-50 dark:hover:bg-slate-800\'',
        '            }`}',
        '          >',
        '            Semua ({subjects.length})',
        '          </button>',
        '        </div>',
        '',
        '        <div className="relative sm:w-64">',
        '          <MagnifyingGlass className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />',
        '          <input',
        '            type="text"',
        '            value={searchQuery}',
        '            onChange={(e) => setSearchQuery(e.target.value)}',
        '            placeholder="Cari kode atau nama mapel..."',
        '            className="w-full pl-8 pr-3 py-1.5 text-xs bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 text-slate-800 dark:text-slate-200 placeholder-slate-400 dark:placeholder-slate-500"',
        '          />',
        '        </div>',
        '      </div>'
      ],
      [
        '      {/* Filter Tabs & MagnifyingGlass Bar */}',
        '      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-[var(--ds-surface)] p-2.5 rounded-2xl border border-[var(--ds-border)] shadow-2xs">',
        '        <div className="flex items-center gap-1 overflow-x-auto">',
        '          <button',
        '            type="button"',
        '            onClick={() => setFilterTab(\'ACTIVE\')}',
        '            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer whitespace-nowrap ${',
        '              filterTab === \'ACTIVE\'',
        '                ? \'bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800\'',
        '                : \'text-[var(--ds-text-muted)] hover:bg-[var(--ds-surface-muted)] hover:text-[var(--ds-text)]\'',
        '            }`}',
        '          >',
        '            Aktif ({activeCount})',
        '          </button>',
        '          <button',
        '            type="button"',
        '            onClick={() => setFilterTab(\'ARCHIVED\')}',
        '            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer whitespace-nowrap ${',
        '              filterTab === \'ARCHIVED\'',
        '                ? \'bg-amber-50 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300 border border-amber-200 dark:border-amber-800\'',
        '                : \'text-[var(--ds-text-muted)] hover:bg-[var(--ds-surface-muted)] hover:text-[var(--ds-text)]\'',
        '            }`}',
        '          >',
        '            Diarsipkan ({archivedCount})',
        '          </button>',
        '          <button',
        '            type="button"',
        '            onClick={() => setFilterTab(\'ALL\')}',
        '            className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer whitespace-nowrap ${',
        '              filterTab === \'ALL\'',
        '                ? \'bg-[var(--ds-surface-muted)] text-[var(--ds-text)] border border-[var(--ds-border)]\'',
        '                : \'text-[var(--ds-text-muted)] hover:bg-[var(--ds-surface-muted)] hover:text-[var(--ds-text)]\'',
        '            }`}',
        '          >',
        '            Semua ({subjects.length})',
        '          </button>',
        '        </div>',
        '',
        '        <div className="relative sm:w-64">',
        '          <MagnifyingGlass className="w-3.5 h-3.5 text-[var(--ds-text-muted)] absolute left-3 top-1/2 -translate-y-1/2" />',
        '          <input',
        '            type="text"',
        '            value={searchQuery}',
        '            onChange={(e) => setSearchQuery(e.target.value)}',
        '            placeholder="Cari kode atau nama mapel..."',
        '            className="w-full pl-8 pr-3 py-1.5 text-xs bg-[var(--ds-surface-muted)] border border-[var(--ds-border)] rounded-xl focus:outline-none focus:ring-2 focus:ring-emerald-500 text-[var(--ds-text)] placeholder:text-[var(--ds-text-muted)]"',
        '          />',
        '        </div>',
        '      </div>'
      ]
    ],
    // Empty state
    [
      [
        '      {/* Grid of Subject Cards */}',
        '      {filteredSubjects.length === 0 ? (',
        '        <div className="bg-white dark:bg-slate-900 border border-slate-200/90 dark:border-slate-800 rounded-2xl p-10 text-center">',
        '          <BookOpen className="w-10 h-10 text-slate-300 dark:text-slate-600 mx-auto mb-3" />',
        '          <h3 className="text-sm font-bold text-slate-700 dark:text-slate-300">',
        '            {searchQuery ? \'Mata pelajaran tidak ditemukan\' : \'Belum ada mata pelajaran\'}',
        '          </h3>',
        '          <p className="text-xs text-slate-400 dark:text-slate-500 mt-1 max-w-sm mx-auto">'
      ],
      [
        '      {/* Grid of Subject Cards */}',
        '      {filteredSubjects.length === 0 ? (',
        '        <div className="bg-[var(--ds-surface)] border border-[var(--ds-border)] rounded-2xl p-10 text-center">',
        '          <BookOpen className="w-10 h-10 text-[var(--ds-text-muted)] opacity-60 mx-auto mb-3" />',
        '          <h3 className="text-sm font-bold text-[var(--ds-text)]">',
        '            {searchQuery ? \'Mata pelajaran tidak ditemukan\' : \'Belum ada mata pelajaran\'}',
        '          </h3>',
        '          <p className="text-xs text-[var(--ds-text-muted)] mt-1 max-w-sm mx-auto">'
      ]
    ],
    // Card item wrapper & border
    [
      [
        '              <div',
        '                key={sub.id}',
        '                className={`p-5 rounded-2xl bg-white dark:bg-slate-900 border transition-all flex flex-col justify-between shadow-2xs hover:shadow-sm ${',
        '                  isArchived',
        '                    ? \'border-slate-200/60 dark:border-slate-800/60 opacity-80\'',
        '                    : \'border-slate-200/90 dark:border-slate-800 hover:border-emerald-300 dark:hover:border-emerald-700\'',
        '                }`}',
        '              >'
      ],
      [
        '              <div',
        '                key={sub.id}',
        '                className={`p-5 rounded-2xl bg-[var(--ds-surface)] border transition-all flex flex-col justify-between shadow-2xs hover:shadow-sm ${',
        '                  isArchived',
        '                    ? \'border-[var(--ds-border)] opacity-80\'',
        '                    : \'border-[var(--ds-border)] hover:border-emerald-300 dark:hover:border-emerald-700\'',
        '                }`}',
        '              >'
      ]
    ],
    // Card title & footer
    [
      [
        '                  <h3 className="font-bold text-base text-slate-800 dark:text-slate-100 leading-snug">',
        '                    {sub.name}',
        '                  </h3>',
        '                </div>',
        '',
        '                <div className="mt-5 pt-3 border-t border-slate-100 dark:border-slate-800/80 flex items-center justify-between text-xs">',
        '                  <span className="text-[11px] text-slate-400 dark:text-slate-500 font-mono">',
        '                    ID: {sub.id.slice(0, 6)}...',
        '                  </span>',
        '',
        '                  {/* Actions: Edit, Archive/Restore, Delete */}',
        '                  <div className="flex items-center gap-1">',
        '                    <button',
        '                      type="button"',
        '                      onClick={() => handleOpenEdit(sub)}',
        '                      title="Ubah Mata Pelajaran"',
        '                      className="p-1.5 rounded-lg text-slate-500 hover:text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-950/60 transition-colors cursor-pointer"',
        '                    >',
        '                      <PencilSimple className="w-3.5 h-3.5" />',
        '                    </button>',
        '',
        '                    <button',
        '                      type="button"',
        '                      onClick={() => handleToggleArchive(sub)}',
        '                      title={isArchived ? "Pulihkan / Aktifkan Kembali" : "Arsipkan Mata Pelajaran"}',
        '                      disabled={archiving}',
        '                      className={`p-1.5 rounded-lg transition-colors cursor-pointer ${',
        '                        isArchived ',
        '                          ? \'text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950/60\' ',
        '                          : \'text-slate-500 hover:text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950/60\'',
        '                      }`}',
        '                    >',
        '                      {isArchived ? (',
        '                        <ArrowCounterClockwise className="w-3.5 h-3.5" />',
        '                      ) : (',
        '                        <Archive className="w-3.5 h-3.5" />',
        '                      )}',
        '                    </button>',
        '',
        '                    <button',
        '                      type="button"',
        '                      onClick={() => handleRequestDelete(sub)}',
        '                      title="Hapus Mata Pelajaran"',
        '                      className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/60 transition-colors cursor-pointer"',
        '                    >',
        '                      <Trash className="w-3.5 h-3.5" />',
        '                    </button>',
        '                  </div>'
      ],
      [
        '                  <h3 className="font-bold text-base text-[var(--ds-text)] leading-snug">',
        '                    {sub.name}',
        '                  </h3>',
        '                </div>',
        '',
        '                <div className="mt-5 pt-3 border-t border-[var(--ds-border)] flex items-center justify-between text-xs">',
        '                  <span className="text-[11px] text-[var(--ds-text-muted)] font-mono">',
        '                    ID: {sub.id.slice(0, 6)}...',
        '                  </span>',
        '',
        '                  {/* Actions: Edit, Archive/Restore, Delete */}',
        '                  <div className="flex items-center gap-1">',
        '                    <button',
        '                      type="button"',
        '                      onClick={() => handleOpenEdit(sub)}',
        '                      title="Ubah Mata Pelajaran"',
        '                      className="p-1.5 rounded-lg text-[var(--ds-text-muted)] hover:text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-950/60 transition-colors cursor-pointer"',
        '                    >',
        '                      <PencilSimple className="w-3.5 h-3.5" />',
        '                    </button>',
        '',
        '                    <button',
        '                      type="button"',
        '                      onClick={() => handleToggleArchive(sub)}',
        '                      title={isArchived ? "Pulihkan / Aktifkan Kembali" : "Arsipkan Mata Pelajaran"}',
        '                      disabled={archiving}',
        '                      className={`p-1.5 rounded-lg transition-colors cursor-pointer ${',
        '                        isArchived ',
        '                          ? \'text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950/60\' ',
        '                          : \'text-[var(--ds-text-muted)] hover:text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950/60\'',
        '                      }`}',
        '                    >',
        '                      {isArchived ? (',
        '                        <ArrowCounterClockwise className="w-3.5 h-3.5" />',
        '                      ) : (',
        '                        <Archive className="w-3.5 h-3.5" />',
        '                      )}',
        '                    </button>',
        '',
        '                    <button',
        '                      type="button"',
        '                      onClick={() => handleRequestDelete(sub)}',
        '                      title="Hapus Mata Pelajaran"',
        '                      className="p-1.5 rounded-lg text-[var(--ds-text-muted)] hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/60 transition-colors cursor-pointer"',
        '                    >',
        '                      <Trash className="w-3.5 h-3.5" />',
        '                    </button>',
        '                  </div>'
      ]
    ],
    // Modal input & labels
    [
      [
        '            <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">',
        '              Kode Mata Pelajaran <span className="text-rose-500">*</span>',
        '            </label>',
        '            <input',
        '              type="text"',
        '              required',
        '              value={code}',
        '              onChange={e => setCode(e.target.value)}',
        '              placeholder="Contoh: ENG / MAT / BIO / PAI"',
        '              className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs uppercase text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-emerald-500"',
        '            />',
        '            <p className="text-[11px] text-slate-400 dark:text-slate-500 mt-1">',
        '              Kode singkat untuk penamaan jadwal & header rapor.',
        '            </p>',
        '          </div>',
        '',
        '          <div>',
        '            <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">',
        '              Nama Lengkap Mata Pelajaran <span className="text-rose-500">*</span>',
        '            </label>',
        '            <input',
        '              type="text"',
        '              required',
        '              value={name}',
        '              onChange={e => setName(e.target.value)}',
        '              placeholder="Contoh: Bahasa Inggris Peminatan"',
        '              className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-emerald-500"',
        '            />',
        '          </div>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-slate-100 dark:border-slate-800">',
        '            <button',
        '              type="button"',
        '              disabled={loading}',
        '              onClick={() => {',
        '                setModalOpen(false);',
        '                setEditingSubject(null);',
        '              }}',
        '              className="px-3 py-2 rounded-xl text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 text-xs font-medium cursor-pointer"',
        '            >'
      ],
      [
        '            <label className="block text-xs font-semibold text-[var(--ds-text)] mb-1.5">',
        '              Kode Mata Pelajaran <span className="text-rose-500">*</span>',
        '            </label>',
        '            <input',
        '              type="text"',
        '              required',
        '              value={code}',
        '              onChange={e => setCode(e.target.value)}',
        '              placeholder="Contoh: ENG / MAT / BIO / PAI"',
        '              className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-xs uppercase text-[var(--ds-text)] focus:outline-none focus:ring-2 focus:ring-emerald-500"',
        '            />',
        '            <p className="text-[11px] text-[var(--ds-text-muted)] mt-1">',
        '              Kode singkat untuk penamaan jadwal & header rapor.',
        '            </p>',
        '          </div>',
        '',
        '          <div>',
        '            <label className="block text-xs font-semibold text-[var(--ds-text)] mb-1.5">',
        '              Nama Lengkap Mata Pelajaran <span className="text-rose-500">*</span>',
        '            </label>',
        '            <input',
        '              type="text"',
        '              required',
        '              value={name}',
        '              onChange={e => setName(e.target.value)}',
        '              placeholder="Contoh: Bahasa Inggris Peminatan"',
        '              className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-xs text-[var(--ds-text)] focus:outline-none focus:ring-2 focus:ring-emerald-500"',
        '            />',
        '          </div>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-[var(--ds-border)]">',
        '            <button',
        '              type="button"',
        '              disabled={loading}',
        '              onClick={() => {',
        '                setModalOpen(false);',
        '                setEditingSubject(null);',
        '              }}',
        '              className="px-3 py-2 rounded-xl text-[var(--ds-text-muted)] hover:text-[var(--ds-text)] hover:bg-[var(--ds-surface-muted)] text-xs font-medium cursor-pointer"',
        '            >'
      ]
    ],
    // Blocked delete modal
    [
      [
        '          <div className="p-3 bg-slate-50 dark:bg-slate-800/50 rounded-xl text-xs text-slate-600 dark:text-slate-400 border border-slate-100 dark:border-slate-800">',
        '            <span className="font-semibold text-slate-800 dark:text-slate-200 block mb-1">',
        '              Solusi Terbaik Berdasarkan Standar Data Madrasah:',
        '            </span>',
        '            Gunakan tombol <strong>Arsipkan</strong> untuk menyembunyikan mata pelajaran ini dari formulir pembuatan jadwal baru, tanpa merusak atau menghilangkan riwayat nilai rapor dan presensi siswa yang sudah tersimpan.',
        '          </div>',
        '',
        '          <div className="flex justify-end gap-2 pt-2">',
        '            <button',
        '              type="button"',
        '              onClick={() => setDeleteBlockedModal(null)}',
        '              className="px-4 py-2 rounded-xl bg-slate-200 dark:bg-slate-700 text-slate-700 dark:text-slate-200 text-xs font-semibold hover:bg-slate-300 dark:hover:bg-slate-600 cursor-pointer"',
        '            >',
        '              Tutup',
        '            </button>'
      ],
      [
        '          <div className="p-3 bg-[var(--ds-surface-muted)] rounded-xl text-xs text-[var(--ds-text-muted)] border border-[var(--ds-border)]">',
        '            <span className="font-semibold text-[var(--ds-text)] block mb-1">',
        '              Solusi Terbaik Berdasarkan Standar Data Madrasah:',
        '            </span>',
        '            Gunakan tombol <strong>Arsipkan</strong> untuk menyembunyikan mata pelajaran ini dari formulir pembuatan jadwal baru, tanpa merusak atau menghilangkan riwayat nilai rapor dan presensi siswa yang sudah tersimpan.',
        '          </div>',
        '',
        '          <div className="flex justify-end gap-2 pt-2">',
        '            <button',
        '              type="button"',
        '              onClick={() => setDeleteBlockedModal(null)}',
        '              className="px-4 py-2 rounded-xl bg-[var(--ds-surface-muted)] text-[var(--ds-text)] text-xs font-semibold hover:bg-[var(--ds-surface)] border border-[var(--ds-border)] cursor-pointer"',
        '            >',
        '              Tutup',
        '            </button>'
      ]
    ]
  ];
  replaceLinesInFile(file, replacements);
}

// ========================================================
// 3. TeachingAssignmentsPage.tsx
// ========================================================
{
  const file = 'src/features/master/TeachingAssignmentsPage.tsx';
  const replacements = [
    // Header title & subtitle
    [
      [
        '          <h1 className="text-xl font-bold text-slate-800 dark:text-zinc-100 tracking-tight flex items-center gap-2">',
        '            <Briefcase className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />',
        '            Plotting & Jadwal Mengajar',
        '          </h1>',
        '          <p className="text-xs text-slate-500 dark:text-zinc-400 mt-1">'
      ],
      [
        '          <h1 className="text-xl font-bold text-[var(--ds-text)] tracking-tight flex items-center gap-2">',
        '            <Briefcase className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />',
        '            Plotting & Jadwal Mengajar',
        '          </h1>',
        '          <p className="text-xs text-[var(--ds-text-muted)] mt-1">'
      ]
    ],
    // Filter tabs container & tab buttons
    [
      [
        '          {/* Tabs Filter */}',
        '          <div className="flex bg-slate-100 dark:bg-neutral-900 p-1 rounded-xl border border-slate-200 dark:border-neutral-800 text-xs">',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ACTIVE\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ACTIVE\'',
        '                  ? \'bg-white dark:bg-neutral-800 text-slate-900 dark:text-white shadow-xs\'',
        '                  : \'text-slate-500 hover:text-slate-800 dark:text-zinc-400\'',
        '              }`}',
        '            >',
        '              Aktif ({teachingAssignments.filter(a => !a.isArchived && a.isActive !== false).length})',
        '            </button>',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ARCHIVED\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ARCHIVED\'',
        '                  ? \'bg-white dark:bg-neutral-800 text-slate-900 dark:text-white shadow-xs\'',
        '                  : \'text-slate-500 hover:text-slate-800 dark:text-zinc-400\'',
        '              }`}',
        '            >',
        '              Arsip ({teachingAssignments.filter(a => a.isArchived || a.isActive === false).length})',
        '            </button>',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ALL\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ALL\'',
        '                  ? \'bg-white dark:bg-neutral-800 text-slate-900 dark:text-white shadow-xs\'',
        '                  : \'text-slate-500 hover:text-slate-800 dark:text-zinc-400\'',
        '              }`}',
        '            >',
        '              Semua ({teachingAssignments.length})',
        '            </button>',
        '          </div>'
      ],
      [
        '          {/* Tabs Filter */}',
        '          <div className="flex bg-[var(--ds-surface-muted)] p-1 rounded-xl border border-[var(--ds-border)] text-xs">',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ACTIVE\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ACTIVE\'',
        '                  ? \'bg-[var(--ds-surface-elevated)] text-[var(--ds-text)] shadow-xs\'',
        '                  : \'text-[var(--ds-text-muted)] hover:text-[var(--ds-text)]\'',
        '              }`}',
        '            >',
        '              Aktif ({teachingAssignments.filter(a => !a.isArchived && a.isActive !== false).length})',
        '            </button>',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ARCHIVED\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ARCHIVED\'',
        '                  ? \'bg-[var(--ds-surface-elevated)] text-[var(--ds-text)] shadow-xs\'',
        '                  : \'text-[var(--ds-text-muted)] hover:text-[var(--ds-text)]\'',
        '              }`}',
        '            >',
        '              Arsip ({teachingAssignments.filter(a => a.isArchived || a.isActive === false).length})',
        '            </button>',
        '            <button',
        '              type="button"',
        '              onClick={() => setFilterTab(\'ALL\')}',
        '              className={`px-3 py-1.5 rounded-lg font-semibold transition-all cursor-pointer ${',
        '                filterTab === \'ALL\'',
        '                  ? \'bg-[var(--ds-surface-elevated)] text-[var(--ds-text)] shadow-xs\'',
        '                  : \'text-[var(--ds-text-muted)] hover:text-[var(--ds-text)]\'',
        '              }`}',
        '            >',
        '              Semua ({teachingAssignments.length})',
        '            </button>',
        '          </div>'
      ]
    ],
    // Empty state
    [
      [
        '      {filteredAssignments.length === 0 ? (',
        '        <div className="bg-white dark:bg-neutral-950 border border-dashed border-slate-200 dark:border-neutral-800 rounded-3xl p-10 text-center">',
        '          <div className="w-12 h-12 rounded-2xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-100 dark:border-emerald-900/50 flex items-center justify-center text-emerald-600 dark:text-emerald-400 mx-auto mb-3">',
        '            <Stack className="w-6 h-6" />',
        '          </div>',
        '          <h3 className="font-bold text-sm text-slate-800 dark:text-zinc-200">',
        '            {filterTab === \'ARCHIVED\' ? \'Tidak ada penugasan diarsipkan\' : \'Belum ada plotting pengajaran\'}',
        '          </h3>',
        '          <p className="text-xs text-slate-500 dark:text-zinc-400 mt-1 max-w-sm mx-auto">'
      ],
      [
        '      {filteredAssignments.length === 0 ? (',
        '        <div className="bg-[var(--ds-surface)] border border-dashed border-[var(--ds-border)] rounded-3xl p-10 text-center">',
        '          <div className="w-12 h-12 rounded-2xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-100 dark:border-emerald-900/50 flex items-center justify-center text-emerald-600 dark:text-emerald-400 mx-auto mb-3">',
        '            <Stack className="w-6 h-6" />',
        '          </div>',
        '          <h3 className="font-bold text-sm text-[var(--ds-text)]">',
        '            {filterTab === \'ARCHIVED\' ? \'Tidak ada penugasan diarsipkan\' : \'Belum ada plotting pengajaran\'}',
        '          </h3>',
        '          <p className="text-xs text-[var(--ds-text-muted)] mt-1 max-w-sm mx-auto">'
      ]
    ],
    // Card item wrapper & border
    [
      [
        '              <div',
        '                key={assign.id}',
        '                className={`p-5 rounded-2xl bg-white dark:bg-neutral-950 border shadow-2xs transition-all flex flex-col justify-between group ${',
        '                  isArchived ',
        '                    ? \'border-dashed border-slate-300 dark:border-neutral-800 opacity-80\' ',
        '                    : \'border-slate-200/90 dark:border-neutral-800 hover:border-emerald-300 dark:hover:border-emerald-800\'',
        '                }`}',
        '              >'
      ],
      [
        '              <div',
        '                key={assign.id}',
        '                className={`p-5 rounded-2xl bg-[var(--ds-surface)] border shadow-2xs transition-all flex flex-col justify-between group ${',
        '                  isArchived ',
        '                    ? \'border-dashed border-[var(--ds-border)] opacity-80\' ',
        '                    : \'border-[var(--ds-border)] hover:border-emerald-300 dark:hover:border-emerald-800\'',
        '                }`}',
        '              >'
      ]
    ],
    // Class badge & mapel code
    [
      [
        '                    <span className={`px-2.5 py-1 rounded-lg border font-bold text-xs ${',
        '                      isArchived',
        '                        ? \'bg-slate-100 dark:bg-neutral-800 border-slate-200 dark:border-neutral-700 text-slate-600 dark:text-zinc-400\'',
        '                        : \'bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-100 dark:border-emerald-500/40 text-emerald-700 dark:text-emerald-400\'',
        '                    }`}>',
        '                      Kelas {assign.className}',
        '                    </span>',
        '                    <div className="flex items-center gap-1.5">',
        '                      {isArchived && (',
        '                        <span className="text-[10px] font-bold text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/60 border border-amber-200 dark:border-amber-800/60 px-2 py-0.5 rounded">',
        '                          Diarsipkan',
        '                        </span>',
        '                      )}',
        '                      <span className="text-[11px] font-mono font-bold text-slate-400 dark:text-zinc-400 bg-slate-100 dark:bg-neutral-900 px-2 py-0.5 rounded">',
        '                        {assign.subjectCode || \'MAPEL\'}',
        '                      </span>',
        '                    </div>',
        '                  </div>',
        '',
        '                  <h3 className="font-bold text-base text-slate-800 dark:text-zinc-100">{assign.subjectName}</h3>',
        '                  <p className="text-xs text-slate-500 dark:text-zinc-400 mt-0.5">'
      ],
      [
        '                    <span className={`px-2.5 py-1 rounded-lg border font-bold text-xs ${',
        '                      isArchived',
        '                        ? \'bg-[var(--ds-surface-muted)] border-[var(--ds-border)] text-[var(--ds-text-muted)]\'',
        '                        : \'bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-100 dark:border-emerald-500/40 text-emerald-700 dark:text-emerald-400\'',
        '                    }`}>',
        '                      Kelas {assign.className}',
        '                    </span>',
        '                    <div className="flex items-center gap-1.5">',
        '                      {isArchived && (',
        '                        <span className="text-[10px] font-bold text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-950/60 border border-amber-200 dark:border-amber-800/60 px-2 py-0.5 rounded">',
        '                          Diarsipkan',
        '                        </span>',
        '                      )}',
        '                      <span className="text-[11px] font-mono font-bold text-[var(--ds-text-muted)] bg-[var(--ds-surface-muted)] px-2 py-0.5 rounded">',
        '                        {assign.subjectCode || \'MAPEL\'}',
        '                      </span>',
        '                    </div>',
        '                  </div>',
        '',
        '                  <h3 className="font-bold text-base text-[var(--ds-text)]">{assign.subjectName}</h3>',
        '                  <p className="text-xs text-[var(--ds-text-muted)] mt-0.5">'
      ]
    ],
    // Schedule info block
    [
      [
        '                  {/* Schedule info block */}',
        '                  <div className="mt-3.5 pt-3 border-t border-slate-100 dark:border-neutral-800 space-y-1.5 text-xs">',
        '                    <div className="flex items-center gap-2 text-slate-700 dark:text-zinc-300">',
        '                      <CalendarBlank className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400 shrink-0" />',
        '                      <span className="font-semibold">',
        '                        {assign.dayOfWeek ? `Hari ${assign.dayOfWeek}` : <span className="text-slate-400 dark:text-zinc-500 italic font-normal">Hari belum diatur</span>}',
        '                      </span>',
        '                    </div>',
        '',
        '                    <div className="flex items-center gap-2 text-slate-700 dark:text-zinc-300">',
        '                      <Clock className="w-3.5 h-3.5 text-amber-500 shrink-0" />',
        '                      <span>',
        '                        {assign.timeSlot ? assign.timeSlot : <span className="text-slate-400 dark:text-zinc-500 italic">Jam belum diatur</span>}',
        '                      </span>',
        '                    </div>',
        '',
        '                    {assign.room ? (',
        '                      <div className="flex items-center gap-2 text-slate-700 dark:text-zinc-300">',
        '                        <MapPin className="w-3.5 h-3.5 text-emerald-500 shrink-0" />',
        '                        <span>{assign.room}</span>',
        '                      </div>',
        '                    ) : null}',
        '                  </div>',
        '                </div>',
        '',
        '                <div className="mt-4 pt-3 border-t border-slate-100 dark:border-neutral-800 flex items-center justify-between">',
        '                  <span className={`text-xs font-medium ${isArchived ? \'text-slate-400 dark:text-zinc-500\' : \'text-emerald-600 dark:text-emerald-400\'}`}>',
        '                    Status: {isArchived ? \'Nonaktif / Arsip\' : \'Aktif\'}',
        '                  </span>',
        '                  <div className="flex items-center gap-1">',
        '                    {!isArchived ? (',
        '                      <>',
        '                        <button',
        '                          type="button"',
        '                          onClick={() => handleOpenEdit(assign)}',
        '                          className="p-1.5 rounded-lg text-slate-400 hover:text-emerald-600 dark:hover:text-emerald-400 hover:bg-slate-100 dark:hover:bg-neutral-900 transition-colors cursor-pointer"',
        '                          title="Edit Jadwal & Penugasan"',
        '                        >',
        '                          <PencilSimple className="w-4 h-4" />',
        '                        </button>',
        '                        <button',
        '                          type="button"',
        '                          disabled={archiving}',
        '                          onClick={() => handleArchive(assign)}',
        '                          className="p-1.5 rounded-lg text-slate-400 hover:text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950/40 transition-colors cursor-pointer"',
        '                          title="Arsipkan Penugasan"',
        '                        >',
        '                          <Archive className="w-4 h-4" />',
        '                        </button>',
        '                      </>',
        '                    ) : (',
        '                      <button',
        '                        type="button"',
        '                        disabled={archiving}',
        '                        onClick={() => handleUnarchive(assign)}',
        '                        className="px-2 py-1 rounded-lg text-xs font-semibold text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60 flex items-center gap-1 transition-colors cursor-pointer"',
        '                        title="Aktifkan Kembali"',
        '                      >',
        '                        <ArrowCounterClockwise className="w-3.5 h-3.5" />',
        '                        <span>Aktifkan</span>',
        '                      </button>',
        '                    )}',
        '',
        '                    <button',
        '                      type="button"',
        '                      onClick={() => handleRequestDelete(assign)}',
        '                      className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 transition-colors cursor-pointer"',
        '                      title="Hapus Penugasan"',
        '                    >',
        '                      <Trash className="w-4 h-4" />',
        '                    </button>',
        '                  </div>'
      ],
      [
        '                  {/* Schedule info block */}',
        '                  <div className="mt-3.5 pt-3 border-t border-[var(--ds-border)] space-y-1.5 text-xs">',
        '                    <div className="flex items-center gap-2 text-[var(--ds-text)]">',
        '                      <CalendarBlank className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400 shrink-0" />',
        '                      <span className="font-semibold">',
        '                        {assign.dayOfWeek ? `Hari ${assign.dayOfWeek}` : <span className="text-[var(--ds-text-muted)] italic font-normal">Hari belum diatur</span>}',
        '                      </span>',
        '                    </div>',
        '',
        '                    <div className="flex items-center gap-2 text-[var(--ds-text)]">',
        '                      <Clock className="w-3.5 h-3.5 text-amber-500 shrink-0" />',
        '                      <span>',
        '                        {assign.timeSlot ? assign.timeSlot : <span className="text-[var(--ds-text-muted)] italic">Jam belum diatur</span>}',
        '                      </span>',
        '                    </div>',
        '',
        '                    {assign.room ? (',
        '                      <div className="flex items-center gap-2 text-[var(--ds-text)]">',
        '                        <MapPin className="w-3.5 h-3.5 text-emerald-500 shrink-0" />',
        '                        <span>{assign.room}</span>',
        '                      </div>',
        '                    ) : null}',
        '                  </div>',
        '                </div>',
        '',
        '                <div className="mt-4 pt-3 border-t border-[var(--ds-border)] flex items-center justify-between">',
        '                  <span className={`text-xs font-medium ${isArchived ? \'text-[var(--ds-text-muted)]\' : \'text-emerald-600 dark:text-emerald-400\'}`}>',
        '                    Status: {isArchived ? \'Nonaktif / Arsip\' : \'Aktif\'}',
        '                  </span>',
        '                  <div className="flex items-center gap-1">',
        '                    {!isArchived ? (',
        '                      <>',
        '                        <button',
        '                          type="button"',
        '                          onClick={() => handleOpenEdit(assign)}',
        '                          className="p-1.5 rounded-lg text-[var(--ds-text-muted)] hover:text-emerald-600 dark:hover:text-emerald-400 hover:bg-[var(--ds-surface-muted)] transition-colors cursor-pointer"',
        '                          title="Edit Jadwal & Penugasan"',
        '                        >',
        '                          <PencilSimple className="w-4 h-4" />',
        '                        </button>',
        '                        <button',
        '                          type="button"',
        '                          disabled={archiving}',
        '                          onClick={() => handleArchive(assign)}',
        '                          className="p-1.5 rounded-lg text-[var(--ds-text-muted)] hover:text-amber-600 hover:bg-amber-50 dark:hover:bg-amber-950/40 transition-colors cursor-pointer"',
        '                          title="Arsipkan Penugasan"',
        '                        >',
        '                          <Archive className="w-4 h-4" />',
        '                        </button>',
        '                      </>',
        '                    ) : (',
        '                      <button',
        '                        type="button"',
        '                        disabled={archiving}',
        '                        onClick={() => handleUnarchive(assign)}',
        '                        className="px-2 py-1 rounded-lg text-xs font-semibold text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800/60 flex items-center gap-1 transition-colors cursor-pointer"',
        '                        title="Aktifkan Kembali"',
        '                      >',
        '                        <ArrowCounterClockwise className="w-3.5 h-3.5" />',
        '                        <span>Aktifkan</span>',
        '                      </button>',
        '                    )}',
        '',
        '                    <button',
        '                      type="button"',
        '                      onClick={() => handleRequestDelete(assign)}',
        '                      className="p-1.5 rounded-lg text-[var(--ds-text-muted)] hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 transition-colors cursor-pointer"',
        '                      title="Hapus Penugasan"',
        '                    >',
        '                      <Trash className="w-4 h-4" />',
        '                    </button>',
        '                  </div>'
      ]
    ],
    // Modal Add/Edit inputs
    [
      [
        '            <label className="block text-xs font-semibold text-slate-700 dark:text-zinc-300 mb-1.5 flex items-center justify-between">',
        '              <span>Pilih Kelas <span className="text-rose-500">*</span></span>',
        '              {assignmentUsage?.isUsed && (',
        '                <span className="text-[10px] text-amber-600 dark:text-amber-400 font-normal flex items-center gap-1">',
        '                  <Lock className="w-3 h-3" /> Terkunci (Ada Riwayat)',
        '                </span>',
        '              )}',
        '            </label>',
        '            <select',
        '              value={selectedClassId}',
        '              disabled={Boolean(assignmentUsage?.isUsed)}',
        '              onChange={e => setSelectedClassId(e.target.value)}',
        '              className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 text-slate-800 dark:text-zinc-200 text-xs focus:ring-2 focus:ring-emerald-500 disabled:opacity-60 disabled:bg-slate-100 dark:disabled:bg-neutral-800"',
        '            >',
        '              {classes',
        '                .filter(c => (c.academicYearId === activeAcademicYear?.id && !c.isArchived) || c.id === editingAssignment?.classId)',
        '                .map(c => (',
        '                  <option key={c.id} value={c.id}>Kelas {c.name} (Tingkat {c.gradeLevel}){c.isArchived ? \' [Diarsipkan]\' : \'\'}</option>',
        '                ))}',
        '            </select>',
        '          </div>',
        '',
        '          <div>',
        '            <label className="block text-xs font-semibold text-slate-700 dark:text-zinc-300 mb-1.5 flex items-center justify-between">',
        '              <span>Pilih Mata Pelajaran <span className="text-rose-500">*</span></span>',
        '              {assignmentUsage?.isUsed && (',
        '                <span className="text-[10px] text-amber-600 dark:text-amber-400 font-normal flex items-center gap-1">',
        '                  <Lock className="w-3 h-3" /> Terkunci (Ada Riwayat)',
        '                </span>',
        '              )}',
        '            </label>',
        '            <select',
        '              value={selectedSubjectId}',
        '              disabled={Boolean(assignmentUsage?.isUsed)}',
        '              onChange={e => setSelectedSubjectId(e.target.value)}',
        '              className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-900 text-slate-800 dark:text-zinc-200 text-xs focus:ring-2 focus:ring-emerald-500 disabled:opacity-60 disabled:bg-slate-100 dark:disabled:bg-neutral-800"',
        '            >',
        '              {subjects.map(s => (',
        '                <option key={s.id} value={s.id}>{s.name} ({s.code})</option>',
        '              ))}',
        '            </select>',
        '          </div>',
        '',
        '          {/* Schedule Configuration Group */}',
        '          <div className="p-3.5 bg-slate-50 dark:bg-neutral-900 rounded-2xl border border-slate-200/80 dark:border-neutral-800 space-y-3">',
        '            <h4 className="text-xs font-bold text-slate-700 dark:text-zinc-300 flex items-center gap-1.5">',
        '              <Clock className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />',
        '              Pengaturan Jadwal Mingguan (Opsional)',
        '            </h4>',
        '',
        '            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">',
        '              <div>',
        '                <label className="block text-[11px] font-medium text-slate-600 dark:text-zinc-400 mb-1">',
        '                  Hari Mengajar',
        '                </label>',
        '                <select',
        '                  value={dayOfWeek}',
        '                  onChange={e => setDayOfWeek(e.target.value)}',
        '                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-950 text-slate-800 dark:text-zinc-200 text-xs focus:ring-2 focus:ring-emerald-500"',
        '                >',
        '                  <option value="">-- Belum Diatur --</option>',
        '                  {DAYS_OF_WEEK.map(d => (',
        '                    <option key={d} value={d}>Hari {d}</option>',
        '                  ))}',
        '                </select>',
        '              </div>',
        '',
        '              <div>',
        '                <label className="block text-[11px] font-medium text-slate-600 dark:text-zinc-400 mb-1">',
        '                  Jam / Sesi Mengajar',
        '                </label>',
        '                <input',
        '                  type="text"',
        '                  placeholder="Contoh: 07:30 - 09:00"',
        '                  value={timeSlot}',
        '                  onChange={e => setTimeSlot(e.target.value)}',
        '                  className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-950 text-slate-800 dark:text-zinc-200 text-xs focus:ring-2 focus:ring-emerald-500 placeholder:text-slate-400"',
        '                />',
        '              </div>',
        '            </div>',
        '',
        '            <div>',
        '              <label className="block text-[11px] font-medium text-slate-600 dark:text-zinc-400 mb-1">',
        '                Ruangan / Tempat (Opsional)',
        '              </label>',
        '              <input',
        '                type="text"',
        '                placeholder="Contoh: Ruang X-A / Lab Komputer"',
        '                value={room}',
        '                onChange={e => setRoom(e.target.value)}',
        '                className="w-full px-3 py-2 rounded-xl border border-slate-300 dark:border-neutral-700 bg-white dark:bg-neutral-950 text-slate-800 dark:text-zinc-200 text-xs focus:ring-2 focus:ring-emerald-500 placeholder:text-slate-400"',
        '              />',
        '            </div>',
        '          </div>',
        '',
        '          <div className="p-3 bg-slate-50 dark:bg-neutral-900 rounded-xl text-xs text-slate-500 dark:text-zinc-400 space-y-1">',
        '            <p><strong>Tahun Ajaran:</strong> {activeAcademicYear?.label}</p>',
        '            <p><strong>Semester:</strong> {activeSemester}</p>',
        '            <p><strong>Guru Pengampu:</strong> {user?.email}</p>',
        '          </div>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-slate-100 dark:border-neutral-800">',
        '            <button',
        '              type="button"',
        '              onClick={() => setModalOpen(false)}',
        '              className="px-3 py-2 rounded-xl text-slate-600 dark:text-zinc-300 hover:bg-slate-100 dark:hover:bg-neutral-800 text-xs font-medium cursor-pointer"',
        '            >'
      ],
      [
        '            <label className="block text-xs font-semibold text-[var(--ds-text)] mb-1.5 flex items-center justify-between">',
        '              <span>Pilih Kelas <span className="text-rose-500">*</span></span>',
        '              {assignmentUsage?.isUsed && (',
        '                <span className="text-[10px] text-amber-600 dark:text-amber-400 font-normal flex items-center gap-1">',
        '                  <Lock className="w-3 h-3" /> Terkunci (Ada Riwayat)',
        '                </span>',
        '              )}',
        '            </label>',
        '            <select',
        '              value={selectedClassId}',
        '              disabled={Boolean(assignmentUsage?.isUsed)}',
        '              onChange={e => setSelectedClassId(e.target.value)}',
        '              className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs focus:ring-2 focus:ring-emerald-500 disabled:opacity-60 disabled:bg-[var(--ds-surface-muted)]"',
        '            >',
        '              {classes',
        '                .filter(c => (c.academicYearId === activeAcademicYear?.id && !c.isArchived) || c.id === editingAssignment?.classId)',
        '                .map(c => (',
        '                  <option key={c.id} value={c.id}>Kelas {c.name} (Tingkat {c.gradeLevel}){c.isArchived ? \' [Diarsipkan]\' : \'\'}</option>',
        '                ))}',
        '            </select>',
        '          </div>',
        '',
        '          <div>',
        '            <label className="block text-xs font-semibold text-[var(--ds-text)] mb-1.5 flex items-center justify-between">',
        '              <span>Pilih Mata Pelajaran <span className="text-rose-500">*</span></span>',
        '              {assignmentUsage?.isUsed && (',
        '                <span className="text-[10px] text-amber-600 dark:text-amber-400 font-normal flex items-center gap-1">',
        '                  <Lock className="w-3 h-3" /> Terkunci (Ada Riwayat)',
        '                </span>',
        '              )}',
        '            </label>',
        '            <select',
        '              value={selectedSubjectId}',
        '              disabled={Boolean(assignmentUsage?.isUsed)}',
        '              onChange={e => setSelectedSubjectId(e.target.value)}',
        '              className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs focus:ring-2 focus:ring-emerald-500 disabled:opacity-60 disabled:bg-[var(--ds-surface-muted)]"',
        '            >',
        '              {subjects.map(s => (',
        '                <option key={s.id} value={s.id}>{s.name} ({s.code})</option>',
        '              ))}',
        '            </select>',
        '          </div>',
        '',
        '          {/* Schedule Configuration Group */}',
        '          <div className="p-3.5 bg-[var(--ds-surface-muted)] rounded-2xl border border-[var(--ds-border)] space-y-3">',
        '            <h4 className="text-xs font-bold text-[var(--ds-text)] flex items-center gap-1.5">',
        '              <Clock className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />',
        '              Pengaturan Jadwal Mingguan (Opsional)',
        '            </h4>',
        '',
        '            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">',
        '              <div>',
        '                <label className="block text-[11px] font-medium text-[var(--ds-text-muted)] mb-1">',
        '                  Hari Mengajar',
        '                </label>',
        '                <select',
        '                  value={dayOfWeek}',
        '                  onChange={e => setDayOfWeek(e.target.value)}',
        '                  className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs focus:ring-2 focus:ring-emerald-500"',
        '                >',
        '                  <option value="">-- Belum Diatur --</option>',
        '                  {DAYS_OF_WEEK.map(d => (',
        '                    <option key={d} value={d}>Hari {d}</option>',
        '                  ))}',
        '                </select>',
        '              </div>',
        '',
        '              <div>',
        '                <label className="block text-[11px] font-medium text-[var(--ds-text-muted)] mb-1">',
        '                  Jam / Sesi Mengajar',
        '                </label>',
        '                <input',
        '                  type="text"',
        '                  placeholder="Contoh: 07:30 - 09:00"',
        '                  value={timeSlot}',
        '                  onChange={e => setTimeSlot(e.target.value)}',
        '                  className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs focus:ring-2 focus:ring-emerald-500 placeholder:text-[var(--ds-text-muted)]"',
        '                />',
        '              </div>',
        '            </div>',
        '',
        '            <div>',
        '              <label className="block text-[11px] font-medium text-[var(--ds-text-muted)] mb-1">',
        '                Ruangan / Tempat (Opsional)',
        '              </label>',
        '              <input',
        '                type="text"',
        '                placeholder="Contoh: Ruang X-A / Lab Komputer"',
        '                value={room}',
        '                onChange={e => setRoom(e.target.value)}',
        '                className="w-full px-3 py-2 rounded-xl border border-[var(--ds-border)] bg-[var(--ds-surface)] text-[var(--ds-text)] text-xs focus:ring-2 focus:ring-emerald-500 placeholder:text-[var(--ds-text-muted)]"',
        '              />',
        '            </div>',
        '          </div>',
        '',
        '          <div className="p-3 bg-[var(--ds-surface-muted)] rounded-xl text-xs text-[var(--ds-text-muted)] space-y-1">',
        '            <p><strong>Tahun Ajaran:</strong> {activeAcademicYear?.label}</p>',
        '            <p><strong>Semester:</strong> {activeSemester}</p>',
        '            <p><strong>Guru Pengampu:</strong> {user?.email}</p>',
        '          </div>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-[var(--ds-border)]">',
        '            <button',
        '              type="button"',
        '              onClick={() => setModalOpen(false)}',
        '              className="px-3 py-2 rounded-xl text-[var(--ds-text-muted)] hover:text-[var(--ds-text)] hover:bg-[var(--ds-surface-muted)] text-xs font-medium cursor-pointer"',
        '            >'
      ]
    ],
    // Delete confirm dialog strong
    [
      [
        '            Apakah Anda yakin ingin menghapus tugas mengajar <strong className="font-semibold text-slate-800 dark:text-slate-100">&quot;{assignmentToDelete?.subjectName} - Kelas {assignmentToDelete?.className}&quot;</strong>?'
      ],
      [
        '            Apakah Anda yakin ingin menghapus tugas mengajar <strong className="font-semibold text-[var(--ds-text)]">&quot;{assignmentToDelete?.subjectName} - Kelas {assignmentToDelete?.className}&quot;</strong>?'
      ]
    ],
    // Delete blocked dialog
    [
      [
        '          <p className="text-xs text-slate-600 dark:text-zinc-400 leading-relaxed">',
        '            Menghapus penugasan ini akan merusak integritas data rekap jurnal KBM atau nilai siswa yang sudah tercatat.',
        '            Sebagai alternatif yang aman, Anda disarankan untuk <strong>mengarsipkan</strong> penugasan ini sehingga tidak lagi muncul di menu transaksi aktif namun tetap aman di riwayat data.',
        '          </p>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-slate-100 dark:border-neutral-800">',
        '            <button',
        '              type="button"',
        '              onClick={() => setDeleteBlockedModal(null)}',
        '              className="px-3 py-2 rounded-xl text-slate-600 dark:text-zinc-300 hover:bg-slate-100 dark:hover:bg-neutral-800 text-xs font-medium cursor-pointer"',
        '            >'
      ],
      [
        '          <p className="text-xs text-[var(--ds-text-muted)] leading-relaxed">',
        '            Menghapus penugasan ini akan merusak integritas data rekap jurnal KBM atau nilai siswa yang sudah tercatat.',
        '            Sebagai alternatif yang aman, Anda disarankan untuk <strong>mengarsipkan</strong> penugasan ini sehingga tidak lagi muncul di menu transaksi aktif namun tetap aman di riwayat data.',
        '          </p>',
        '',
        '          <div className="flex justify-end gap-2 pt-3 border-t border-[var(--ds-border)]">',
        '            <button',
        '              type="button"',
        '              onClick={() => setDeleteBlockedModal(null)}',
        '              className="px-3 py-2 rounded-xl text-[var(--ds-text-muted)] hover:text-[var(--ds-text)] hover:bg-[var(--ds-surface-muted)] text-xs font-medium cursor-pointer"',
        '            >'
      ]
    ]
  ];
  replaceLinesInFile(file, replacements);
}

console.log('ALL STAGE 5.1 REPLACEMENTS COMPLETE!');
